### ISSUE TITLE
continuation of the timer?

### ISSUE THREAD

**Issue by zAfLu** [0blu/Timer#1]
Hi,

will you continue the dev on this timer? Or are the recent changes just some "one time" changes? :)

**Comment by 0blu** [comment]
Hey,
i honestly dont know.
The reason for this update was only to run "Timer" on the new sourcemod version.
I also wrote to zipcore, thaht i update his code but he didn't respond yet.
What do you mean with "continue the dev"?

**Comment by zAfLu** [comment]
New features, bug fixes n stuff like that.

**Comment by 0blu** [comment]
No i will not adding new features, maybe i will fix some bugs if i have the time to do this.
