### ISSUE TITLE
timer-rankings

### ISSUE THREAD

**Issue by Caaine** [0blu/Timer#2]
i have a Problem with the rankings 
is the autoreload bugged?
http://images.akamai.steamusercontent.com/ugc/361778221406896283/20EAC1B8721247A51635808DD36E8CF8ACB96F42/

when reload the plugin working fine
sm_rcon sm plugins reload timer-rankings
http://images.akamai.steamusercontent.com/ugc/361778221406896899/2C9F11E601D6005D5E4858DE71092825F95F7D6F/

**Comment by 0blu** [comment]
When does the error come exactly?
When you switch the map?

**Comment by Caaine** [comment]
by server start
by map change

**Comment by 0blu** [comment]
Are there any errors in the Console?

**Comment by Caaine** [comment]
no errors...
enable the ranking debug S:

The Rank refresh on TAB is the problem

my settings:

```
    //Use time with deaths to sort players in scoreboard for best times?
    "hud_use_death_rank"                    "1"

    //Use rank with frags to sort players in scoreboard for most points?
    "hud_use_frag_points_rank"              "1"

    //Use clan tag to display info ( Disable this if you only want the players rank to be displayed as clan tag! )
    "hud_use_clan_tag"                      "0"

    //Use clan tag to display current style
    "hud_use_clan_tag_style"                "0"

    //Use clan tag to display running timer (displays best time if timer is stopped)
    "hud_use_clan_tag_time"                 "0"

    //Change player MVPs for (points/100)? Max MVPs are 9,999 due to an engine limit.
    "hud_use_mvp_stars"                     "0"
```

**Comment by 0blu** [comment]
At the moment i have no clue.
I will add you at Steam.

**Comment by 0blu** [comment]
https://github.com/0blu/Timer/issues/3
