### ISSUE TITLE
[BUG] pushes dont push

### ISSUE THREAD

**Issue by fabian-bickel** [0blu/Timer#4]
Push stones like the green ones in lego2 dont push the player up

Edit:
i think its line 577-578 in timer-physics.sp

it works with:

 if(onground && !oldgroundstatus && g_bAutoDisable[client])
SetEntityGravity(client, g_Physics[style][StyleGravity]);

**Comment by fabian-bickel** [comment]
i think its line 577-578 in timer-physics.sp

**Comment by 0blu** [comment]
I will check this later, but i am pretty sure that what you think it it, its not.

Are you using the Timer in csgo?

**Comment by fabian-bickel** [comment]
Yes i use in csgo.

And the Problem ist every time you use cmd it sets the gravity and so you dont get pushed up. And its only on autobhop but with this its a short fix hope you find a better fix for that.

**Comment by brlight** [comment]
Thank you Fabian! Your solution worked 100%

**Comment by 0blu** [comment]
Umm sorry for the long delay, I will push this fix soon.
Thanks Fabian.
